# Generated by Django 5.0.7 on 2024-08-27 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watchlist_app', '0002_streamplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='Watchlist_app.streamplatform'),
            preserve_default=False,
        ),
    ]
